# Generated by Django 2.0.6 on 2020-10-15 16:53

from django.db import migrations, models
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emr', '0001_initial'),
        ('drug', '0001_initial'),
        ('drug_instruction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmrDrug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=20)),
                ('drug', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='emr_drug_drug', to='drug.Drug')),
                ('drug_instruction', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='emr_drug_drug_instruction', to='drug_instruction.DrugInstruction')),
                ('emr', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='emr_drug_emr', to='emr.Emr')),
            ],
            options={
                'db_table': 'emr_drug',
            },
        ),
    ]
