# Generated by Django 2.0.6 on 2020-10-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr_drug', '0002_emrdrug_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emrdrug',
            name='unit_price',
        ),
    ]
