# Generated by Django 2.0.6 on 2020-10-15 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInstruction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instruction', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'drug_instruction',
            },
        ),
    ]
