# Generated by Django 2.0.6 on 2020-10-15 00:43

from django.db import migrations, models
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='notification_receiver', to='user.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='notification_sender', to='user.User')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
