# Generated by Django 2.0.6 on 2020-10-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='a', max_length=191),
            preserve_default=False,
        ),
    ]
