# Generated by Django 2.0.6 on 2020-10-15 16:17

from django.db import migrations, models
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emr',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='initialized', max_length=20)),
                ('total', models.DecimalField(decimal_places=0, max_digits=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='emr_created_by', to='user.User')),
                ('patient', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='emr_patient', to='user.User')),
                ('physician', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='emr_physician', to='user.User')),
            ],
            options={
                'db_table': 'emr',
            },
        ),
        migrations.CreateModel(
            name='EmrImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=191)),
                ('emr', models.ForeignKey(null=True, on_delete=django.db.models.expressions.Case, related_name='emr_image', to='emr.Emr')),
            ],
            options={
                'db_table': 'emr_image',
            },
        ),
    ]
