# Generated by Django 2.0.6 on 2020-12-18 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugDosageForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'drug_dosage_form',
            },
        ),
    ]
