# Generated by Django 2.0.6 on 2020-10-15 01:38

from django.db import migrations, models
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='visit_created_by', to='user.User')),
                ('patient', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='visit_patient', to='user.User')),
                ('room', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='visit_room', to='room.Room')),
            ],
            options={
                'db_table': 'visit',
            },
        ),
    ]
