# Generated by Django 2.0.6 on 2020-10-15 00:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('price', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
            options={
                'db_table': 'service',
            },
        ),
    ]
