# Generated by Django 2.0.6 on 2020-10-15 16:27

from django.db import migrations, models
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drug_unit', '0001_initial'),
        ('drug_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=191, unique=True)),
                ('name', models.CharField(max_length=191)),
                ('price', models.DecimalField(decimal_places=0, max_digits=20)),
                ('drug_category', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='drug_drug_category', to='drug_category.DrugCategory')),
                ('drug_unit', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='drug_drug_unit', to='drug_unit.DrugUnit')),
            ],
            options={
                'db_table': 'drug',
            },
        ),
    ]
