# Generated by Django 2.0.6 on 2020-10-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_drug_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='code',
            field=models.CharField(max_length=191),
        ),
    ]
