# Generated by Django 2.0.6 on 2020-10-15 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.CharField(max_length=20)),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'working_hours',
            },
        ),
    ]
