# Generated by Django 2.0.6 on 2020-10-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_hours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
