# Generated by Django 2.0.6 on 2020-10-15 16:55

from django.db import migrations, models
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disease', '0001_initial'),
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmrDisease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='emr_disease_disease', to='disease.Disease')),
                ('emr', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='emr_disease_emr', to='emr.Emr')),
            ],
            options={
                'db_table': 'emr_disease',
            },
        ),
    ]
