# Generated by Django 2.0.6 on 2020-10-14 17:30

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.expressions
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=191, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(blank=True, max_length=191, null=True)),
                ('last_name', models.CharField(blank=True, max_length=191, null=True)),
                ('address', models.CharField(blank=True, max_length=191, null=True)),
                ('is_verified_email', models.BooleanField(default=False)),
                ('is_verified_phone', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=191)),
                ('last_reset_password_at', models.DateTimeField(null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.CharField(blank=True, max_length=191, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='user_role', to='role.Role')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
