# Generated by Django 2.0.6 on 2020-10-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_registration',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
