# Generated by Django 2.0.6 on 2020-10-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_disease_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='code',
            field=models.CharField(max_length=191),
        ),
    ]
